

CREATE TABLE IF NOT EXISTS Cliente (
  id bigint primary key NOT NULL AUTO_INCREMENT,
  dataNasc VARCHAR(100) NOT NULL,
  telefoneFixo VARCHAR(100) NOT NULL,
  tipoSanguineo VARCHAR(100) NOT NULL,
  nome VARCHAR(100) NOT NULL,
  idade VARCHAR(100) NOT NULL,
  cpf VARCHAR(100) NOT NULL,
  rg VARCHAR(100) NOT NULL,
  signo VARCHAR(100) NOT NULL,
  mae VARCHAR(100) NOT NULL,
  pai VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(100) NOT NULL,
  cep VARCHAR(100) NOT NULL,
  numero VARCHAR(100) NOT NULL,
  celular VARCHAR(100) NOT NULL,
  altura VARCHAR(100) NOT NULL,
  peso VARCHAR(100) NOT NULL,
  cor VARCHAR(100) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  estado VARCHAR(100) NOT NULL
);